### ISSUE TITLE
Use configuration files instead of exporting variables

### ISSUE THREAD

**Issue by alejandro-colomar** [secobau/docker-aws#27]
Providing a configuration file (the default location could be `/etc/docker-aws/config.sh`) would be a more standard way of providing all the definitions needed for the scripts, instead of exporting them all by the user.

**Comment by alejandro-colomar** [comment]
Using a configuration file would imply that the error code `${EX_USAGE}` would have to be changed to `${EX_CONFIG}`

**Comment by scolomar** [comment]
> Providing a configuration file (the default location could be `/etc/docker-aws/config.sh`) would be a more standard way of providing all the definitions needed for the scripts, instead of exporting them all by the user.

I do not see how this could be achieved. 

The end users need to choose their own configuration and if their repo is private there will be no way to use this code without a previous fork.

Exporting is not necessary. We are leaving to the users the possibility to create their own script to set up the environment variables.

**Comment by alejandro-colomar** [comment]
This is how:

https://github.com/alejandro-colomar/www/blob/master/etc/docker-aws/config.sh

https://github.com/alejandro-colomar/www/blob/master/bin/deploy_aws.sh

**Comment by scolomar** [comment]
> https://github.com/alejandro-colomar/www/blob/master/bin/deploy_aws.sh

`source	etc/docker-aws/config.sh;`
In what repository would that file be located?

**Comment by alejandro-colomar** [comment]
> > https://github.com/alejandro-colomar/www/blob/master/bin/deploy_aws.sh
> 
> `source etc/docker-aws/config.sh;`
> In what repository would that file be located?

In the repository of the user.  Like that one.  You can have an example here in /share/examples/
