### ISSUE TITLE
Recreate tag v1.0

### ISSUE THREAD

**Issue by alejandro-colomar** [secobau/docker-aws#8]
https://github.com/secobau/docker-aws/tree/d1d9b732080ee60f123b05f054c6b72393797fe7

This tag is needed by repositories depending on it.  It was at that comit.

**Comment by scolomar** [comment]
Is it even possible? Otherwise please upgrade.

**Comment by alejandro-colomar** [comment]
> Is it even possible? Otherwise please upgrade.

https://stackoverflow.com/questions/18216991/create-a-tag-in-a-github-repository

```
git checkout <commit>
git tag <tag_name> [-m "msg"]
git push origin <tag_name>
```

**Comment by scolomar** [comment]
Fixed.
`git checkout v1.0 && git push origin v1.0`

**Comment by alejandro-colomar** [comment]
> Fixed.
> `git checkout v1.0 && git push origin v1.0`

That worked because you didn't clean your local copy.  If you had done `git fetch -p` you would have needed the code above.
